configScript.log("setting scriptable gameconfig");
configScript.BENDED_DEFORMATION_END = 1000;
configScript.BENDED_DEFORMATION_START = 0.01;
configScript.BENDED_STYLING_PRESET =1;
configScript.SPEED_TOREAL_RATIO=2.0;
configScript.FOVY_INITIAL = 30;
configScript.FOVY_ADDITION_MAX = 20;
configScript.ENGINE_FREQUENCY_LOW =5000;
configScript.AUDIO_PITCH_FACTOR=0.5;
configScript.DAMPING_FORCE = 1500.0;
configScript.CAMERA_NAVI_EYE_POSITION_Z = 20.0;
configScript.CAMERA_NAVI_CENTER_POSITION_Z = 20.0; 
//configScript.CAMERA_EYE_POSITION_Z = 0.0;

// SETTINGS
//<int> BENDED_VIEWS_ACTIVATED
//<int> BENDED_VIEWS_DEACTIVATED
//<int> TIME_TO_ACTIVATE_BENDED_VIEWS
//<int> BENDED_STYLING_PRESET
//<int> BENDED_DEFORMATION_END
//<double> BENDED_DEFORMATION_START
//<double> SPEED_TOREAL_RATIO
//<double> RESPAWN_DURATION
//<double> GAME_START_COUNTDOWN_DURATION
//<double> RANDOM_NUMBER_DURATION
//<double> RANDOM_NUMBER_INTERVAL
//<double> FOVY_INITIAL
//<double> FOVY_INITIAL_NAVI
//<double> FOVY_ADDITION_MAX
//<double> ENGINE_FREQUENCY_LOW
//<double> AUDIO_PITCH_FACTOR
//<double> BIKE_STEERING_INCREMENT
//<double> BIKE_STEERINGCLAMP
//<double> CAMERA_POSITION_OFFSET_X
//<double> CAMERA_POSITION_OFFSET_Y
//<double> CAMERA_POSITION_OFFSET_Z
//<double> CAMERA_EYE_POSITION_X
//<double> CAMERA_EYE_POSITION_Y
//<double> CAMERA_EYE_POSITION_Z
//<double> DAMPING_FORCE
//<double> CAMERA_NAVI_EYE_POSITION_Z
//double> CAMERA_NAVI_CENTER_POSITION_Z